repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.16.5
    hooks:
      # Run the linter.
      - id: ruff-check
        exclude: ^(submodules/|qnlab/solver/external_files/ntqn\.py$)
      # Run the formatter.
      - id: ruff-format
        exclude: ^(submodules/|qnlab/solver/external_files/ntqn\.py$)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v2.3.1'
    hooks:
       - id: mypy
         exclude: ^submodules/
         additional_dependencies: [types-PyYAML==6.0.12.20250516]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'PYTHONPATH=./ .venv/bin/pytest test'
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        exclude: ^doc/(.+\.pdf|.+\.gif)$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: nbstripout (strip notebook outputs)
        description: "Strip output cells and large embedded content from Jupyter notebooks (.ipynb)"
        files: \.ipynb$
